# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from all_msgs/Curve.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Curve(genpy.Message):
  _md5sum = "9a544adf692f69bcc100499d862d09b5"
  _type = "all_msgs/Curve"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Float32 x_start 
std_msgs/Float32 x_end 
std_msgs/Float32 a 
std_msgs/Float32 b 
std_msgs/Float32 c 
std_msgs/Float32 d 
================================================================================
MSG: std_msgs/Float32
float32 data"""
  __slots__ = ['x_start','x_end','a','b','c','d']
  _slot_types = ['std_msgs/Float32','std_msgs/Float32','std_msgs/Float32','std_msgs/Float32','std_msgs/Float32','std_msgs/Float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x_start,x_end,a,b,c,d

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Curve, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x_start is None:
        self.x_start = std_msgs.msg.Float32()
      if self.x_end is None:
        self.x_end = std_msgs.msg.Float32()
      if self.a is None:
        self.a = std_msgs.msg.Float32()
      if self.b is None:
        self.b = std_msgs.msg.Float32()
      if self.c is None:
        self.c = std_msgs.msg.Float32()
      if self.d is None:
        self.d = std_msgs.msg.Float32()
    else:
      self.x_start = std_msgs.msg.Float32()
      self.x_end = std_msgs.msg.Float32()
      self.a = std_msgs.msg.Float32()
      self.b = std_msgs.msg.Float32()
      self.c = std_msgs.msg.Float32()
      self.d = std_msgs.msg.Float32()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.x_start.data, _x.x_end.data, _x.a.data, _x.b.data, _x.c.data, _x.d.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.x_start is None:
        self.x_start = std_msgs.msg.Float32()
      if self.x_end is None:
        self.x_end = std_msgs.msg.Float32()
      if self.a is None:
        self.a = std_msgs.msg.Float32()
      if self.b is None:
        self.b = std_msgs.msg.Float32()
      if self.c is None:
        self.c = std_msgs.msg.Float32()
      if self.d is None:
        self.d = std_msgs.msg.Float32()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.x_start.data, _x.x_end.data, _x.a.data, _x.b.data, _x.c.data, _x.d.data,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.x_start.data, _x.x_end.data, _x.a.data, _x.b.data, _x.c.data, _x.d.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.x_start is None:
        self.x_start = std_msgs.msg.Float32()
      if self.x_end is None:
        self.x_end = std_msgs.msg.Float32()
      if self.a is None:
        self.a = std_msgs.msg.Float32()
      if self.b is None:
        self.b = std_msgs.msg.Float32()
      if self.c is None:
        self.c = std_msgs.msg.Float32()
      if self.d is None:
        self.d = std_msgs.msg.Float32()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.x_start.data, _x.x_end.data, _x.a.data, _x.b.data, _x.c.data, _x.d.data,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
