# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from all_msgs/Lane.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import all_msgs.msg
import std_msgs.msg

class Lane(genpy.Message):
  _md5sum = "fd19b0521fb882c8cb26592918c30eb4"
  _type = "all_msgs/Lane"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Int32   lane_id 
Curve            curve 
EndPoints        end_points 
std_msgs/Int32   measure_status  
std_msgs/Float32 confidence 

================================================================================
MSG: std_msgs/Int32
int32 data
================================================================================
MSG: all_msgs/Curve
std_msgs/Float32 x_start 
std_msgs/Float32 x_end 
std_msgs/Float32 a 
std_msgs/Float32 b 
std_msgs/Float32 c 
std_msgs/Float32 d 
================================================================================
MSG: std_msgs/Float32
float32 data
================================================================================
MSG: all_msgs/EndPoints
Point2f start 
Point2f end 

================================================================================
MSG: all_msgs/Point2f
std_msgs/Float32 x 
std_msgs/Float32 y 
"""
  __slots__ = ['lane_id','curve','end_points','measure_status','confidence']
  _slot_types = ['std_msgs/Int32','all_msgs/Curve','all_msgs/EndPoints','std_msgs/Int32','std_msgs/Float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       lane_id,curve,end_points,measure_status,confidence

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Lane, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.lane_id is None:
        self.lane_id = std_msgs.msg.Int32()
      if self.curve is None:
        self.curve = all_msgs.msg.Curve()
      if self.end_points is None:
        self.end_points = all_msgs.msg.EndPoints()
      if self.measure_status is None:
        self.measure_status = std_msgs.msg.Int32()
      if self.confidence is None:
        self.confidence = std_msgs.msg.Float32()
    else:
      self.lane_id = std_msgs.msg.Int32()
      self.curve = all_msgs.msg.Curve()
      self.end_points = all_msgs.msg.EndPoints()
      self.measure_status = std_msgs.msg.Int32()
      self.confidence = std_msgs.msg.Float32()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i10fif().pack(_x.lane_id.data, _x.curve.x_start.data, _x.curve.x_end.data, _x.curve.a.data, _x.curve.b.data, _x.curve.c.data, _x.curve.d.data, _x.end_points.start.x.data, _x.end_points.start.y.data, _x.end_points.end.x.data, _x.end_points.end.y.data, _x.measure_status.data, _x.confidence.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.lane_id is None:
        self.lane_id = std_msgs.msg.Int32()
      if self.curve is None:
        self.curve = all_msgs.msg.Curve()
      if self.end_points is None:
        self.end_points = all_msgs.msg.EndPoints()
      if self.measure_status is None:
        self.measure_status = std_msgs.msg.Int32()
      if self.confidence is None:
        self.confidence = std_msgs.msg.Float32()
      end = 0
      _x = self
      start = end
      end += 52
      (_x.lane_id.data, _x.curve.x_start.data, _x.curve.x_end.data, _x.curve.a.data, _x.curve.b.data, _x.curve.c.data, _x.curve.d.data, _x.end_points.start.x.data, _x.end_points.start.y.data, _x.end_points.end.x.data, _x.end_points.end.y.data, _x.measure_status.data, _x.confidence.data,) = _get_struct_i10fif().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i10fif().pack(_x.lane_id.data, _x.curve.x_start.data, _x.curve.x_end.data, _x.curve.a.data, _x.curve.b.data, _x.curve.c.data, _x.curve.d.data, _x.end_points.start.x.data, _x.end_points.start.y.data, _x.end_points.end.x.data, _x.end_points.end.y.data, _x.measure_status.data, _x.confidence.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.lane_id is None:
        self.lane_id = std_msgs.msg.Int32()
      if self.curve is None:
        self.curve = all_msgs.msg.Curve()
      if self.end_points is None:
        self.end_points = all_msgs.msg.EndPoints()
      if self.measure_status is None:
        self.measure_status = std_msgs.msg.Int32()
      if self.confidence is None:
        self.confidence = std_msgs.msg.Float32()
      end = 0
      _x = self
      start = end
      end += 52
      (_x.lane_id.data, _x.curve.x_start.data, _x.curve.x_end.data, _x.curve.a.data, _x.curve.b.data, _x.curve.c.data, _x.curve.d.data, _x.end_points.start.x.data, _x.end_points.start.y.data, _x.end_points.end.x.data, _x.end_points.end.y.data, _x.measure_status.data, _x.confidence.data,) = _get_struct_i10fif().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i10fif = None
def _get_struct_i10fif():
    global _struct_i10fif
    if _struct_i10fif is None:
        _struct_i10fif = struct.Struct("<i10fif")
    return _struct_i10fif
