// Generated by gencpp from file all_msgs/Indices.msg
// DO NOT EDIT!


#ifndef ALL_MSGS_MESSAGE_INDICES_H
#define ALL_MSGS_MESSAGE_INDICES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int32.h>

namespace all_msgs
{
template <class ContainerAllocator>
struct Indices_
{
  typedef Indices_<ContainerAllocator> Type;

  Indices_()
    : indices()  {
    }
  Indices_(const ContainerAllocator& _alloc)
    : indices(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::std_msgs::Int32_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::std_msgs::Int32_<ContainerAllocator> >> _indices_type;
  _indices_type indices;





  typedef boost::shared_ptr< ::all_msgs::Indices_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::all_msgs::Indices_<ContainerAllocator> const> ConstPtr;

}; // struct Indices_

typedef ::all_msgs::Indices_<std::allocator<void> > Indices;

typedef boost::shared_ptr< ::all_msgs::Indices > IndicesPtr;
typedef boost::shared_ptr< ::all_msgs::Indices const> IndicesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::all_msgs::Indices_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::all_msgs::Indices_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::all_msgs::Indices_<ContainerAllocator1> & lhs, const ::all_msgs::Indices_<ContainerAllocator2> & rhs)
{
  return lhs.indices == rhs.indices;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::all_msgs::Indices_<ContainerAllocator1> & lhs, const ::all_msgs::Indices_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace all_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::all_msgs::Indices_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs::Indices_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs::Indices_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs::Indices_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs::Indices_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs::Indices_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::all_msgs::Indices_<ContainerAllocator> >
{
  static const char* value()
  {
    return "355aaec182bd3a24f494f1ab4a82fd9e";
  }

  static const char* value(const ::all_msgs::Indices_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x355aaec182bd3a24ULL;
  static const uint64_t static_value2 = 0xf494f1ab4a82fd9eULL;
};

template<class ContainerAllocator>
struct DataType< ::all_msgs::Indices_<ContainerAllocator> >
{
  static const char* value()
  {
    return "all_msgs/Indices";
  }

  static const char* value(const ::all_msgs::Indices_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::all_msgs::Indices_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int32[]    indices\n"
"================================================================================\n"
"MSG: std_msgs/Int32\n"
"int32 data\n"
;
  }

  static const char* value(const ::all_msgs::Indices_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::all_msgs::Indices_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.indices);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Indices_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::all_msgs::Indices_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::all_msgs::Indices_<ContainerAllocator>& v)
  {
    s << indent << "indices[]" << std::endl;
    for (size_t i = 0; i < v.indices.size(); ++i)
    {
      s << indent << "  indices[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "    ", v.indices[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALL_MSGS_MESSAGE_INDICES_H
