// Generated by gencpp from file all_msgs/Point3d.msg
// DO NOT EDIT!


#ifndef ALL_MSGS_MESSAGE_POINT3D_H
#define ALL_MSGS_MESSAGE_POINT3D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>

namespace all_msgs
{
template <class ContainerAllocator>
struct Point3d_
{
  typedef Point3d_<ContainerAllocator> Type;

  Point3d_()
    : x()
    , y()
    , z()  {
    }
  Point3d_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , z(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float64_<ContainerAllocator>  _x_type;
  _x_type x;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _y_type;
  _y_type y;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::all_msgs::Point3d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::all_msgs::Point3d_<ContainerAllocator> const> ConstPtr;

}; // struct Point3d_

typedef ::all_msgs::Point3d_<std::allocator<void> > Point3d;

typedef boost::shared_ptr< ::all_msgs::Point3d > Point3dPtr;
typedef boost::shared_ptr< ::all_msgs::Point3d const> Point3dConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::all_msgs::Point3d_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::all_msgs::Point3d_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::all_msgs::Point3d_<ContainerAllocator1> & lhs, const ::all_msgs::Point3d_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::all_msgs::Point3d_<ContainerAllocator1> & lhs, const ::all_msgs::Point3d_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace all_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::all_msgs::Point3d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs::Point3d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs::Point3d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs::Point3d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs::Point3d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs::Point3d_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::all_msgs::Point3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5166234939ddbad7844e2026f79c5fa";
  }

  static const char* value(const ::all_msgs::Point3d_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5166234939ddbadULL;
  static const uint64_t static_value2 = 0x7844e2026f79c5faULL;
};

template<class ContainerAllocator>
struct DataType< ::all_msgs::Point3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "all_msgs/Point3d";
  }

  static const char* value(const ::all_msgs::Point3d_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::all_msgs::Point3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float64 x \n"
"std_msgs/Float64 y \n"
"std_msgs/Float64 z \n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::all_msgs::Point3d_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::all_msgs::Point3d_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Point3d_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::all_msgs::Point3d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::all_msgs::Point3d_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALL_MSGS_MESSAGE_POINT3D_H
