// Generated by gencpp from file all_msgs/Position.msg
// DO NOT EDIT!


#ifndef ALL_MSGS_MESSAGE_POSITION_H
#define ALL_MSGS_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace all_msgs
{
template <class ContainerAllocator>
struct Position_
{
  typedef Position_<ContainerAllocator> Type;

  Position_()
    : latitude(0.0)
    , longitude(0.0)
    , height(0.0)  {
    }
  Position_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::all_msgs::Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::all_msgs::Position_<ContainerAllocator> const> ConstPtr;

}; // struct Position_

typedef ::all_msgs::Position_<std::allocator<void> > Position;

typedef boost::shared_ptr< ::all_msgs::Position > PositionPtr;
typedef boost::shared_ptr< ::all_msgs::Position const> PositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::all_msgs::Position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::all_msgs::Position_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::all_msgs::Position_<ContainerAllocator1> & lhs, const ::all_msgs::Position_<ContainerAllocator2> & rhs)
{
  return lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::all_msgs::Position_<ContainerAllocator1> & lhs, const ::all_msgs::Position_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace all_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::all_msgs::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs::Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs::Position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::all_msgs::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2eb7dcbe507b4e4bd3e8128ce0dc99e1";
  }

  static const char* value(const ::all_msgs::Position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2eb7dcbe507b4e4bULL;
  static const uint64_t static_value2 = 0xd3e8128ce0dc99e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::all_msgs::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "all_msgs/Position";
  }

  static const char* value(const ::all_msgs::Position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::all_msgs::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 latitude\n"
"float64 longitude\n"
"float64 height\n"
;
  }

  static const char* value(const ::all_msgs::Position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::all_msgs::Position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::all_msgs::Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::all_msgs::Position_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALL_MSGS_MESSAGE_POSITION_H
