// Generated by gencpp from file all_msgs/TransResultArray.msg
// DO NOT EDIT!


#ifndef ALL_MSGS_MESSAGE_TRANSRESULTARRAY_H
#define ALL_MSGS_MESSAGE_TRANSRESULTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Float64.h>
#include <all_msgs/TransResult.h>

namespace all_msgs
{
template <class ContainerAllocator>
struct TransResultArray_
{
  typedef TransResultArray_<ContainerAllocator> Type;

  TransResultArray_()
    : header()
    , timestamp()
    , percept_results()  {
    }
  TransResultArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , timestamp(_alloc)
    , percept_results(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _timestamp_type;
  _timestamp_type timestamp;

   typedef std::vector< ::all_msgs::TransResult_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::all_msgs::TransResult_<ContainerAllocator> >> _percept_results_type;
  _percept_results_type percept_results;





  typedef boost::shared_ptr< ::all_msgs::TransResultArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::all_msgs::TransResultArray_<ContainerAllocator> const> ConstPtr;

}; // struct TransResultArray_

typedef ::all_msgs::TransResultArray_<std::allocator<void> > TransResultArray;

typedef boost::shared_ptr< ::all_msgs::TransResultArray > TransResultArrayPtr;
typedef boost::shared_ptr< ::all_msgs::TransResultArray const> TransResultArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::all_msgs::TransResultArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::all_msgs::TransResultArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::all_msgs::TransResultArray_<ContainerAllocator1> & lhs, const ::all_msgs::TransResultArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.timestamp == rhs.timestamp &&
    lhs.percept_results == rhs.percept_results;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::all_msgs::TransResultArray_<ContainerAllocator1> & lhs, const ::all_msgs::TransResultArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace all_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::all_msgs::TransResultArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs::TransResultArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs::TransResultArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs::TransResultArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs::TransResultArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs::TransResultArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::all_msgs::TransResultArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3dc2c2ad61b7400d12ab8d2481f10686";
  }

  static const char* value(const ::all_msgs::TransResultArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3dc2c2ad61b7400dULL;
  static const uint64_t static_value2 = 0x12ab8d2481f10686ULL;
};

template<class ContainerAllocator>
struct DataType< ::all_msgs::TransResultArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "all_msgs/TransResultArray";
  }

  static const char* value(const ::all_msgs::TransResultArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::all_msgs::TransResultArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"std_msgs/Float64 timestamp \n"
"TransResult[] percept_results\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
"================================================================================\n"
"MSG: all_msgs/TransResult\n"
"std_msgs/Header header\n"
"std_msgs/Float64 timestamp \n"
"Point3f          size \n"
"Point3f          center \n"
"Point3f          velocity\n"
"std_msgs/Int32   type \n"
"std_msgs/String detection_name\n"
"int32[] ct\n"
"int32[] tracking\n"
"int32 label_preds\n"
"int32 tracking_id\n"
"int32 age\n"
"int32 active\n"
"================================================================================\n"
"MSG: all_msgs/Point3f\n"
"std_msgs/Float32 x \n"
"std_msgs/Float32 y \n"
"std_msgs/Float32 z \n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
"================================================================================\n"
"MSG: std_msgs/Int32\n"
"int32 data\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::all_msgs::TransResultArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::all_msgs::TransResultArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.timestamp);
      stream.next(m.percept_results);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TransResultArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::all_msgs::TransResultArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::all_msgs::TransResultArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "timestamp: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.timestamp);
    s << indent << "percept_results[]" << std::endl;
    for (size_t i = 0; i < v.percept_results.size(); ++i)
    {
      s << indent << "  percept_results[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::all_msgs::TransResult_<ContainerAllocator> >::stream(s, indent + "    ", v.percept_results[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALL_MSGS_MESSAGE_TRANSRESULTARRAY_H
