(cl:in-package all_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          PRIORITY_ID-VAL
          PRIORITY_ID
          EXIST_CONFIDENCE-VAL
          EXIST_CONFIDENCE
          CENTER-VAL
          CENTER
          CENTER_COV-VAL
          CENTER_COV
          SIZE-VAL
          SIZE
          SIZE_COV-VAL
          SIZE_COV
          DIRECTION-VAL
          DIRECTION
          DIRECTION_COV-VAL
          DIRECTION_COV
          TYPE-VAL
          TYPE
          TYPE_CONFIDENCE-VAL
          TYPE_CONFIDENCE
          ATTENTION_TYPE-VAL
          ATTENTION_TYPE
          MOTION_STATE-VAL
          MOTION_STATE
          LANE_POS-VAL
          LANE_POS
          TRAKCER_ID-VAL
          TRAKCER_ID
          AGE-VAL
          AGE
          VELOCITY-VAL
          VELOCITY
          VELOCITY_COV-VAL
          VELOCITY_COV
          ACCELERATION-VAL
          ACCELERATION
          ACCELERATION_COV-VAL
          ACCELERATION_COV
          ANGLE_VELOCITY-VAL
          ANGLE_VELOCITY
          ANGLE_VELOCITY_COV-VAL
          ANGLE_VELOCITY_COV
          ANGLE_ACCELERATION-VAL
          ANGLE_ACCELERATION
          ANGLE_ACCELERATION_COV-VAL
          ANGLE_ACCELERATION_COV
          ANCHOR-VAL
          ANCHOR
          NEAREST_POINT-VAL
          NEAREST_POINT
))