(cl:in-package all_msgs-msg)
(cl:export '(UNIQUE_ID-VAL
          UNIQUE_ID
          POLYGON-VAL
          POLYGON
          LEFT_POINT_INDEX-VAL
          LEFT_POINT_INDEX
          RIGHT_POINT_INDEX-VAL
          RIGHT_POINT_INDEX
          CLOUD_INDICES-VAL
          CLOUD_INDICES
          LATENT_TYPES-VAL
          LATENT_TYPES
          SIZE_TYPE-VAL
          SIZE_TYPE
          MODE-VAL
          MODE
          IN_ROI-VAL
          IN_ROI
          TRACKING_STATE-VAL
          TRACKING_STATE
          GEO_CENTER-VAL
          GEO_CENTER
          GEO_SIZE-VAL
          GEO_SIZE
          TRAJECTORY-VAL
          TRAJECTORY
          HISTORY_VELOCITY-VAL
          HISTORY_VELOCITY
          HISTORY_TYPE-VAL
          HISTORY_TYPE
          GPS_MODE-VAL
          GPS_MODE
          GPS_INFO-VAL
          GPS_INFO
))